### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by purplecones** [Joanvo/npm-extrapolate#1]
I'm interested in this but have a question. It's not too clear from the docs but I am wondering if I can use this for my use case.

I have set of data points plotted over time(days). Let's say I have 5 days worth of data points, but I want to predict up to 10 days. So depending on how days 1-5 did, will this package give me estimated values for days 6-10?

**Comment by Joanvo** [comment]
Hi Mirza,

Yes, that's the goal of this package, but it will only predict properly if
your function is similar to a polynomial function.

Use the data you have from that 5 days to train:

extrapolate.given(1, value1);
extrapolate.given(2, value2);
[...]

Then use getPoly to get a prediction:

extrapolate.getPoly(6);

Please let me know your feedback. I hope this works for you!

Joan


2017-03-10 22:05 GMT+01:00 Mirza Joldic <notifications@github.com>:

**Comment by purplecones** [comment]
Thanks
